name: Build Unsigned IPA for AltStore

on:
  workflow_dispatch:
    inputs:
      scheme:
        description: Xcode scheme to build
        required: true
      workspace:
        description: Optional .xcworkspace path (e.g., App.xcworkspace). Leave empty to use .xcodeproj discovery.
        required: false
        default: ""
      configuration:
        description: Build configuration
        required: false
        default: Release
  push:
    branches: [ main, master ]

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest
    env:
      CONFIGURATION: ${{ inputs.configuration || 'Release' }}
      SCHEME: ${{ inputs.scheme }}
      WORKSPACE: ${{ inputs.workspace }}
      # Customize if you want a different output name
      IPA_NAME: ${{ inputs.scheme }}.ipa

    steps:
      # ---- Check out sources (with your existing submodules cache) ----
      - name: Cache Git submodules
        uses: actions/cache@v4
        with:
          path: |
            .git/modules
            qemu-tcti
            third-party/SwiftTerm
          key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # ---- Dependencies (SwiftPM and optional CocoaPods) ----
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Set up Ruby for CocoaPods (only if Podfile exists)
        if: hashFiles('**/Podfile') != ''
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install CocoaPods (only if Podfile exists)
        if: hashFiles('**/Podfile') != ''
        run: |
          gem install cocoapods --no-document
          pod install --repo-updat

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --daemon
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix --version

      # - name: Set up Ruby & CocoaPods
      #   run: |
      #     sudo gem install cocoapods
      #     pod install --project-directory=tctiSH

      - name: Build native dependencies (Nix)
        #--command bash build_dependencies.sh
        run: |
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix develop --extra-experimental-features nix-command --extra-experimental-features flakes

      - name: Build and copy tctictl utility
        working-directory: utils/tctictl
        run: |
          bash build_and_copy.sh

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -workspace tctiSH.xcworkspace \
            -scheme tctiSH

      - name: Build unsigned .xcarchive
        run: |
          xcodebuild -workspace tctiSH.xcworkspace \
            -scheme tctiSH \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/tctiSH.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Export unsigned IPA
        run: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingCertificate</key>
            <string></string>
            <key>provisioningProfiles</key>
            <dict/>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/tctiSH.xcarchive \
            -exportPath ${{ github.workspace }}/build/unsigned_ipa \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/unsigned_ipa/*.ipa
